### ISSUE TITLE
[MacOS] Buttons and letters are purple rectangles / UI file issue

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-rei#11]
Not sure if it's know issue, but all buttons and letters are purple rectangles for me :)

<img width="1280" alt="Screenshot 2022-09-11 at 13 33 14" src="https://user-images.githubusercontent.com/26703613/189522937-f69ebccd-8f4d-4e07-9e0a-e96b2942e52b.png">
<img width="1280" alt="Screenshot 2022-09-11 at 13 33 34" src="https://user-images.githubusercontent.com/26703613/189522958-3523b9f3-f508-44de-a1ab-ade532f286c5.png">

_Originally posted by @ondatric in https://github.com/07th-mod/python-patcher/issues/184#issuecomment-1242936044_

**Comment by drojf** [comment]
This is probably a UI file issue (relating to the `sharedassets0.assets` file)

Please send your `sharedassets0.assets.backup` file. 

It should be inside the .app bundle at `HigurashiEp09.app\Contents\Resources\Data\sharedassets0.assets.backup`

If you have the install logs handy, please send those too (should be in your browser downloads)

Note: user has steam version of the game (see [previous issue)](https://github.com/07th-mod/python-patcher/issues/184#issue-1368825192))

**Comment by ondatric** [comment]
Files:

[sharedassets0.assets.backup.zip](https://github.com/07th-mod/higurashi-rei/files/9542336/sharedassets0.assets.backup.zip)
[07th-mod-logs (1).zip](https://github.com/07th-mod/higurashi-rei/files/9542338/07th-mod-logs.1.zip)

**Comment by drojf** [comment]
@ondatric Can you try replacing your sharedassets0.assets with this one?
[Rei-UI_2019.4.3_unix_D54D5922_MacOS.zip](https://github.com/07th-mod/higurashi-rei/files/9542365/Rei-UI_2019.4.3_unix_D54D5922_MacOS.zip)

**Comment by ondatric** [comment]
@drojf Seems like it didn't help.
<img width="1280" alt="Screenshot 2022-09-11 at 14 39 40" src="https://user-images.githubusercontent.com/26703613/189525519-c549100d-5670-4b1f-bfec-de553ba4c67c.png">

**Comment by drojf** [comment]
sorry, I think I made a mistake, can you try this one?
[rei-2019.4.3-macos.zip](https://github.com/07th-mod/higurashi-rei/files/9542392/rei-2019.4.3-macos.zip)

**Comment by ondatric** [comment]
Now it's working fine!
But the font is a little bit strage.
<img width="1280" alt="Screenshot 2022-09-11 at 14 44 51" src="https://user-images.githubusercontent.com/26703613/189525767-1218cc2f-5102-4354-8ed1-742244962489.png">

**Comment by drojf** [comment]
ah I'm so sorry, I was testing something on my setup and I forgot to disable it...let me build it on the server and send you one more time

**Comment by drojf** [comment]
I ended up building it on my computer again, hopefully it isn't messed up like before:

https://07th-mod.com/rikachama/ui/Rei-UI_2019.4.3_mac.7z

**Comment by ondatric** [comment]
Fonts are looking good now

Thank you

**Comment by drojf** [comment]
I've updated
- the installer with the new UI files
- the wiki manual install with the new UI files
- the vanilla archive with the macOS UI files and the ui-editing-scripts scripts have added the mac ui builds

so closing this issue now

**Comment by drojf** [comment]
Tellow suggested to try the Mac sharedassets on linux, and they seem to work.

I'm repoening this issue until I revert the above changes, but then use the Mac sharedassets for unix:
 - revert installer changes
 - revert wiki changes
 - revert the ui-editing-scripts changes
 - modify vanilla archive to make macOS UI file the default for unix
 - replace the unix ui files on the server
 - optionally delete the macOS ui files on the server

**Comment by drojf** [comment]
> optionally delete the macOS ui files on the server

I've done everything except this. Will leave the macos files on the server (and also backup of the old unix files) in case this breaks something so we can revert it easier
