### ISSUE TITLE
new font broke the symbol

### ISSUE THREAD

**Issue by Nudificaistrum** [07th-mod/higurashi-rei#22]
![font](https://github.com/07th-mod/python-patcher/assets/143423720/2f77833e-aafd-4e2d-afe0-175c483b5d44)

**Comment by drojf** [comment]
Which chapter is this from?

**Comment by Nudificaistrum** [comment]
Hirukowashi

**Comment by Nudificaistrum** [comment]
In Rei, irie sprites (iri3_majime2_0, iri3_majime2_1, iri3_majime2_2) need to be fixed.
![Irie_head](https://github.com/07th-mod/python-patcher/assets/143423720/e2e2fa69-3dd1-4655-b2ae-e99a650e8cd0)
Also, I think that line (hirukowashi pc version) is supposed to be Hanyuu's, not Rika.
![rika_line](https://github.com/07th-mod/python-patcher/assets/143423720/39304393-1b78-49f2-8cb8-08980da3b3bf)

**Comment by drojf** [comment]
The issues with the missing characters should be fixed now (translators will need to rebuild their UI files after updating their forks for the https://github.com/07th-mod/ui-editing-scripts repository).

As for the other issues, I've moved them to a separate issue: https://github.com/07th-mod/higurashi-rei/issues/23

**Comment by drojf** [comment]
Previously I responded by generating higher resolution font objects (generated with the wrong font file), which caused some issues.

But after regenerating font objects with the same font as before/without a custom material, the problems were resolved
