### ISSUE TITLE
Different font is used vs previous modded chapters

### ISSUE THREAD

**Issue by drojf** [07th-mod/higurashi-rei#5]
We currently can't patch fonts for this chapter, so the fonts are different from previous chapters.

**Comment by drojf** [comment]
Just to write down the status of this, we actually can patch the fonts now (using a different process). See 

- https://github.com/07th-mod/ui-editing-scripts
- https://07th-mod.com/wiki/developer/sharedassets/ui-editing-scripts/ (search for rei)

On discord I generated a UI file for Rei with the updated fonts, but since it looked very slightly more blurry than previous chapters, I wanted someone else to try it out to see how it looked.

> 
> You can try this wip, but the text looks slightly blurrier than the previous chapters to my eyes.
> 
> Take a backup of your Higurashi When They Cry Hou - Rei\HigurashiEp09_Data\sharedassets0.assets file, then replace it with the one in the attached zip file
> 
> https://1drv.ms/u/s!Ar-lAVeetlqhhKssJRgpOtTJLtp48g?e=9yxjij
> 
> It should look like this once installed: https://1drv.ms/u/s!Ar-lAVeetlqhhKstzKwC-8OxNDuFpA?e=fJdFgZ (open link for high res photo) 
> 
> I can only really tell by A/Bing it against a screenshot of the previous chapter
> 
> I was messing with it yesterday, and can actually make it super sharp, but it reduces the black outline thickness. Our mod has a script command to adjust the outline thickness, but if I use that to make the outline thicker, it makes the text very thin (the white part of the text). Possibly could force the text to be bold in the DLL to compensate but I haven't tried that.

Also see the other thread about general Japanese font improvements for ch1-8: https://github.com/07th-mod/ui-editing-scripts/issues/13#issuecomment-1334900969

> I think I remember when I was playing around with making textures on Unity 5 for Rei, when I tried to make the glyphs too big (I think by default it's like 24 or 26 size, but making something like 50 screwed it up), it affected the font outline (it made it really thin). Then I tried to adjust the  outline in the DLL, which kinda worked, but I forgot whether it was successful or not)

> Should be fine.  Yes, the resolution does affect outline width, but we also have a configuration for that.
> Only minus for making it bigger is file size.  2048*2048 is 4mb, 4096*4096 is 16
> (Unity asset bundle stores these textures uncompressed)

**Comment by Timo654** [comment]
I finished 2 chapters with that font and it seemed fine to me on a 1080p screen, but I didn't compare it side by side to the previous chapters. 

It was perfectly readable however and looked very similar to the previous chapters.

**Comment by drojf** [comment]
I did some testing on Saikoroshi while preparing to use the new font, and I noticed the text overflowing at one point, which I fixed by adjusting the font size/spacing/placement slightly. 

Did you notice this when you were playing (at any time, not just in Saikoroshi)?

It might be just that one scene, but to be safe I made the font similarly sized and spaced to avoid future problems.

I think without adjustment, the vertical line spacing was unintentionally too big, so it helps with that too,

If you want to test the 'fixed' font size, overwrite the `HigurashiEp09_Data/StreamingAssets/Update/init.txt` with this one: [init.txt](https://github.com/07th-mod/higurashi-rei/files/10299282/init.txt), but I think it's good even without further testing.

**Comment by drojf** [comment]
OK, I've pushed the changes now (there was some issue with caching but hopefully if you install via the installer now, it should give you the new fonts).

If you find any problems, please re-open the issue

Also, thanks for chasing this up this issue for me, I don't think I would have gotten around to fixing it otherwise lol

**Comment by Timo654** [comment]
> Did you notice this when you were playing (at any time, not just in Saikoroshi)?

Oh yeah sorry, I forgot to mention. I did have this multiple times. It definitely happened in Saikoroshi and Hirukowashi, but I'm not exactly sure when. I skipped Batsukoishi so no clue if it happened there.

Hopefully it's fixed now, thanks!
